from sqlalchemy import Column, String
from shortuuid import ShortUUID

# DB Base
from abitly.db import Base


class Link(Base):
    """Link Model: Define the Link schema in the data base for the Links table.

    Links is a table to store the information of the all generated links
    with the purpose of don't duplicate or generate new links for stored links.

    Attributes
    ----------

    id : str
        Primary key generated by ShortUUID
    original_url : str
        The original URL to make the redirect.
    generated_url : str
        The URL generated to identify.
    """

    __tablename__ = 'links'
    id = Column(String, primary_key=True)
    original_url = Column(String, unique=True)
    generated_url = Column(String(7), unique=True)

    def __init__(self, original_url=None, generated_url=None):
        """
        Parameters
        ----------

        original_url : str
            The URL received in the request
        generated_url : str
            The URL generated with a length of 7 characters
        """
        self.id = ShortUUID().random(length=10)
        self.original_url = original_url
        self.generated_url = generated_url
